package crawler

import (
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	"io/ioutil"
	"net/http"
	"net/url"
)
type Req struct {
	Status int `json:"status"`
	Error string `json:"error"`
	Data SearchData `json:"data"`
	Errcode int `json:"errcode"`
}

type SearchData struct {
	Info []Info `json:"info"`
}

type Info struct {
	Singername string `json:"singername"`
	Songname string `json:"songname"`
	Hash string `json:"hash"`
	AlbumID string `json:"album_id"`
}

type AutoGenerated struct {
	Status int `json:"status"`
	ErrCode int `json:"err_code"`
	Data Data `json:"data"`
}


var searchApi = "http://mobilecdn.kugou.com/api/v3/search/song?"
var songDetailApi  = "https://wwwapi.kugou.com/yy/index.php?r=play/getdata&dfid=3LjnlA1XAW9s3cB5ld2oVr1V&mid=99467f8a47af4fa16dc26fc68bab9215&platid=4&_=1615257951219"

//获取输入框中的关键字
func getKeyword(c *gin.Context) string {
	var keyword = c.Query("keyword")
	fmt.Print(keyword)
	return keyword
}

func handleSongDetail(searchApi string, c *gin.Context)  Req{
	client, err := http.NewRequest(http.MethodGet, searchApi, nil)
	keyword := getKeyword(c)
	if err != nil {
		panic("请求失败")
	}
	params := make(url.Values)
	params.Add("keyword", keyword)
	client.URL.RawQuery = params.Encode()
	req, err := http.DefaultClient.Do(client)
	defer func() {
		req.Body.Close()
	}()
	if req.StatusCode != 200 {
		panic("返回错误响应")
	}
	body, _ := ioutil.ReadAll(req.Body)
	r := Req{}
	json.Unmarshal(body, &r)
	if r.Status != 1 {
		panic(r.Error)
	}
	return r
}

/*
@des 获取搜索结果的api
@return 返回搜索结果
*/
func getSearchResUrls(c *gin.Context) []string{
	res := handleSongDetail(searchApi, c)
	songs := res.Data.Info
	searchLen := len(songs)
	hashs := make([]string, searchLen)
	albumids :=  make([]string, searchLen)
	searchRes := make([]string, searchLen)
	for k,song := range songs {
		hashs[k] = song.Hash
		albumids[k] = song.AlbumID
	}

	var req, _ = http.NewRequest("GET", songDetailApi, nil)
	q := req.URL.Query()
	for k := range hashs {
		if(k != 0) {
			q.Del("hash")
			q.Del("album_id")
		}
		q.Add("hash",hashs[k])
		q.Add("album_id", albumids[k])
		req.URL.RawQuery = q.Encode()
		searchRes[k] = req.URL.String()
	}

	return searchRes
}

//结构体暂时用飙升榜的，todo 把它们统一到工具方法中
func getSearchDetails(c *gin.Context) []Song{
	urls := getSearchResUrls(c)
	searchSongs := make([]Song, 0)
	for i := range urls {
		req, err := http.Get(urls[i])
		if err != nil {
			fmt.Print("请求搜索接口失败:", err)
		}
		defer func() {
			req.Body.Close()
		}()
		if req.StatusCode != 200 {
			panic("返回错误响应")
		}
		body, _ := ioutil.ReadAll(req.Body)
		song := Song{}
		json.Unmarshal(body, &song)
		searchSongs = append(searchSongs, song) //把每个song存入map中
	}
	return searchSongs

}

func HandleSearch(context *gin.Context) {
	res := getSearchDetails(context)
	context.JSON(http.StatusOK, res) //返回给前端
}




